#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression --message="Removing system configurations related to $app..." --weight=1

ynh_remove_nginx_config
ynh_remove_fpm_config

ynh_secure_remove --file="/etc/logrotate.d/$app"

#=================================================
# REMOVE LOG DIRECTORY
#=================================================
ynh_script_progression --message="Removing the log directory..." --weight=1

ynh_secure_remove --file="/var/log/$app"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Removal of $app completed" --last
